language: haskell
install:
  - "cabal update"
  - "cabal install happy --constraint='transformers<0.5' --jobs"
  - "cabal install code-builder/ rest-stringmap/ rest-client/ rest-core/ rest-example/ rest-gen/ rest-happstack/ rest-snap/ rest-types/ rest-wai/ --dry-run -v3 --max-backjumps=-1 --reorder-goals --enable-tests"
script:
  - "cabal install code-builder/ rest-stringmap/ rest-client/ rest-core/ rest-gen/ rest-happstack/ rest-snap/ rest-types/ rest-wai/ --max-backjumps=-1 --reorder-goals --enable-tests --jobs=1"
  - "(cd rest-core && cabal install --enable-tests --only-d && cabal test)"
  - "(cd rest-gen  && cabal install --enable-tests --only-d && cabal test)"
  - "cabal install rest-example/ -fhappstack -fsnap -fwai --only-dependencies"
  - "cabal install rest-example/ -fhappstack -fsnap -fwai --jobs=1"
  - "rest-example-gen --haskell --target rest-example/client"
  - "rest-example-gen --javascript --target rest-example/client.js"
  - "rest-example-gen --ruby --target rest-example/client.rb"
  - "ruby rest-example/client.rb"
  - "cabal install rest-example/client --jobs=1"
notifications:
  email:
    recipients: travis@silk.co
    on_success: never
    on_failure: change
sudo: false
