language: haskell
install:
  - "cabal install code-builder/ rest-client/ rest-core/ rest-example/ rest-gen/ rest-happstack/ rest-snap/ rest-types/ --dry-run -v3 --max-backjumps=-1"
script:
  - "cabal install code-builder/ rest-client/ rest-core/ rest-example/ rest-gen/ rest-happstack/ rest-snap/ rest-types/ --max-backjumps=-1"
notifications:
  email:
    recipients: travis@silk.co
    on_success: never
    on_failure: change
