resolver: lts-8.5
flags:
  rest-example:
    snap: true
    happstack: true
    wai: true
    gen: true
extra-deps:
- HUnit-1.6.0.0
allow-newer: true
packages:
- code-builder/
- rest-client/
- rest-core/
- rest-example/
- rest-example/client/
- rest-gen/
- rest-happstack/
- rest-snap/
- rest-stringmap/
- rest-types/
- rest-wai/
