resolver: lts-7.0
flags:
  rest-example:
    snap: true
    happstack: true
    wai: true
    gen: true
extra-deps:
- haskell-src-exts-1.18.2
- HUnit-1.4.0.0
- call-stack-0.1.0
packages:
- code-builder/
- rest-client/
- rest-core/
- rest-example/
- rest-example/client/
- rest-gen/
- rest-happstack/
- rest-snap/
- rest-stringmap/
- rest-types/
- rest-wai/
