resolver: lts-6.10
flags:
  rest-example:
    snap: true
    happstack: true
    wai: true
    gen: true
  semigroups:
    bytestring-builder: false
packages:
- code-builder/
- rest-client/
- rest-core/
- rest-example/
- rest-example/client/
- rest-gen/
- rest-happstack/
- rest-snap/
- rest-stringmap/
- rest-types/
- rest-wai/
extra-deps:
- aeson-1.0.0.0
- semigroups-0.18.2
